#ansible-playbook

---

- name: Find and fetch result_txt files
  hosts: awsprod
  become: yes
  gather_facts: false

  vars:
    remote_path: "/home/ec2-user/"
    local_path: "/etc/ansible/txt_fetch/"

  tasks:
    - name: Find txt files
      find:
        paths: "{{ remote_path }}"
        file_type: file
        patterns: "*.txt"
      register: found_files

    - name: Fetch txt files
      fetch:
        src: "{{ item.path }}"
        dest: "{{ local_path }}/{{ item.path | basename }}"
        flat: yes
      with_items: "{{ found_files.files }}"



...
