# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /LOG/addressapi/addressapi_qa.log
  fields:
    service_name: addressapi_qa
    log_name: addressapi_qa
    log_type: service
# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: [[IPADDR]:5044"]

# ================================= Processors =================================
#processors:
#  - add_host_metadata:
#      when.not.contains.tags: forwarded
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~
